name: ecommerce-workflow

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  test_code:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '16.x'  

      - run: npm install --force
      - run: npm run build
             
